name: Auto Update File

on:
  schedule:
    - cron: '0 * * * *'  # প্রতি ঘন্টায় রান হবে (UTC সময়)
  workflow_dispatch:     # ম্যানুয়ালি রান করতেও পারবে

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Update Script
        run: |
          echo "Updated on $(date)" > updated.txt

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add updated.txt
          git commit -m "Auto update: $(date)" || echo "No changes to commit"
          git push
